on:
  push:
    branches:
      - ambulanceInventory
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to main server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        port: 22
        sync: true
        script: ${{ secrets.PULL_SCRIPT }}
    - name: notify on failure
      if: failure()
      run: |
        RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
        "username": "GitHub",
        "content": "Push ox_inventory na główny serwer nie powiódł się!",
        "embeds": null,
        "attachments": []
        }' ${{ secrets.WEBHOOK_URL }})
        echo "Webhook server response: $RESPONSE"
    - name: cleanup
      run: rm -rf ~/.ssh
